name: ziru
description: "Ziru FPS Counter"
publish_to: 'none'
version: 1.1.0+3

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_colorpicker: ^1.0.3
  permission_handler: ^11.3.1
  flutter_overlay_window: ^0.4.4
  shizuku: ^2.0.1
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  device_info_plus: ^10.1.0
  usage_stats: ^1.3.1
  battery_plus: ^5.0.3
  cached_network_image: ^3.3.1
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
